//***********************************************************************************************************
// Copyright ©2014 Bio-Rad Laboratories, Inc. All rights reserved.
//
// This class is part of the CFX Manager API Examples kit. 
//
// This file contains the schema runtime objects used by the example code to represent 
// and manipulate CFX Manager API service schema structures at runtime.
//
// It was generated from the API using the Microsoft XML Schema Definition Tool (xsd.exe) 
//***********************************************************************************************************

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Message", Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd", IsNullable = false)]
public partial class MessageType
{

    private string registrationIDField;

    private object itemField;

    /// <remarks/>
    public string RegistrationID
    {
        get
        {
            return this.registrationIDField;
        }
        set
        {
            this.registrationIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddRepeats", typeof(AddRepeatsType))]
    [System.Xml.Serialization.XmlElementAttribute("AnalysisExport", typeof(AnalysisExportType))]
    [System.Xml.Serialization.XmlElementAttribute("CloseLid", typeof(CloseLidType))]
    [System.Xml.Serialization.XmlElementAttribute("FlashLed", typeof(FlashLedType))]
    [System.Xml.Serialization.XmlElementAttribute("GenerateReport", typeof(GenerateReportType))]
    [System.Xml.Serialization.XmlElementAttribute("OpenLid", typeof(OpenLidType))]
    [System.Xml.Serialization.XmlElementAttribute("PauseRun", typeof(PauseRunType))]
    [System.Xml.Serialization.XmlElementAttribute("QueryBlocks", typeof(QueryInstrumentBlocksType))]
    [System.Xml.Serialization.XmlElementAttribute("RegisterService", typeof(RegisterServiceType))]
    [System.Xml.Serialization.XmlElementAttribute("ResumeRun", typeof(ResumeRunType))]
    [System.Xml.Serialization.XmlElementAttribute("RunProtocol", typeof(RunProtocolType))]
    [System.Xml.Serialization.XmlElementAttribute("ShutDown", typeof(ShutDownType))]
    [System.Xml.Serialization.XmlElementAttribute("SkipStep", typeof(SkipStepType))]
    [System.Xml.Serialization.XmlElementAttribute("StopRun", typeof(StopRunType))]
    [System.Xml.Serialization.XmlElementAttribute("UnRegisterService", typeof(UnRegisterServiceType))]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class AddRepeatsType
{

    private string serialNumberField;

    private int numberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }

    /// <remarks/>
    public int Number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class FirmwareVersionsType
{

    private string pXA270Field;

    private string fX2Field;

    private string hC12Field;

    private string dSPField;

    private string lIDField;

    /// <remarks/>
    public string PXA270
    {
        get
        {
            return this.pXA270Field;
        }
        set
        {
            this.pXA270Field = value;
        }
    }

    /// <remarks/>
    public string FX2
    {
        get
        {
            return this.fX2Field;
        }
        set
        {
            this.fX2Field = value;
        }
    }

    /// <remarks/>
    public string HC12
    {
        get
        {
            return this.hC12Field;
        }
        set
        {
            this.hC12Field = value;
        }
    }

    /// <remarks/>
    public string DSP
    {
        get
        {
            return this.dSPField;
        }
        set
        {
            this.dSPField = value;
        }
    }

    /// <remarks/>
    public string LID
    {
        get
        {
            return this.lIDField;
        }
        set
        {
            this.lIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class SerialNumbersType
{

    private string baseField;

    private string blockField;

    private string shuttleField;

    private string opticalHeadField;

    /// <remarks/>
    public string Base
    {
        get
        {
            return this.baseField;
        }
        set
        {
            this.baseField = value;
        }
    }

    /// <remarks/>
    public string Block
    {
        get
        {
            return this.blockField;
        }
        set
        {
            this.blockField = value;
        }
    }

    /// <remarks/>
    public string Shuttle
    {
        get
        {
            return this.shuttleField;
        }
        set
        {
            this.shuttleField = value;
        }
    }

    /// <remarks/>
    public string OpticalHead
    {
        get
        {
            return this.opticalHeadField;
        }
        set
        {
            this.opticalHeadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class TemperatureUnitsType
{

    private float temperatureField;

    private TemperatureUnits unitsField;

    /// <remarks/>
    public float Temperature
    {
        get
        {
            return this.temperatureField;
        }
        set
        {
            this.temperatureField = value;
        }
    }

    /// <remarks/>
    public TemperatureUnits Units
    {
        get
        {
            return this.unitsField;
        }
        set
        {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public enum TemperatureUnits
{

    /// <remarks/>
    Celcius,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class VolumeUnitsType
{

    private float volumeField;

    private VolumeUnits unitsField;

    /// <remarks/>
    public float Volume
    {
        get
        {
            return this.volumeField;
        }
        set
        {
            this.volumeField = value;
        }
    }

    /// <remarks/>
    public VolumeUnits Units
    {
        get
        {
            return this.unitsField;
        }
        set
        {
            this.unitsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public enum VolumeUnits
{

    /// <remarks/>
    MicroLiter,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class InstrumentBlockType
{

    private ErrorType[] errorArrayField;

    private string serialNumberField;

    private StatusType statusField;

    private int stepField;

    private int stepsField;

    private int cycleField;

    private int cyclesField;

    private VolumeUnitsType sampleVolumeField;

    private TemperatureUnitsType lidTemperatureField;

    private TemperatureUnitsType blockTemperatureField;

    private float estimatedRemainingRunTimeField;

    private string nickNameField;

    private string descriptionField;

    private int rowsField;

    private int columnsField;

    private BlockLetterType letterField;

    private bool dualField;

    private bool realTimeField;

    private string manufacturerField;

    private bool simulatedField;

    private string ripFolderField;

    private MotorizedLidPositionType motorizedLidPositionField;

    private int blockIDField;

    private bool shippingScrewInstalledField;

    private SerialNumbersType serialNumbersField;

    private FirmwareVersionsType firmwareVersionsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ErrorArray")]
    public ErrorType[] ErrorArray
    {
        get
        {
            return this.errorArrayField;
        }
        set
        {
            this.errorArrayField = value;
        }
    }

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }

    /// <remarks/>
    public StatusType Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    public int Step
    {
        get
        {
            return this.stepField;
        }
        set
        {
            this.stepField = value;
        }
    }

    /// <remarks/>
    public int Steps
    {
        get
        {
            return this.stepsField;
        }
        set
        {
            this.stepsField = value;
        }
    }

    /// <remarks/>
    public int Cycle
    {
        get
        {
            return this.cycleField;
        }
        set
        {
            this.cycleField = value;
        }
    }

    /// <remarks/>
    public int Cycles
    {
        get
        {
            return this.cyclesField;
        }
        set
        {
            this.cyclesField = value;
        }
    }

    /// <remarks/>
    public VolumeUnitsType SampleVolume
    {
        get
        {
            return this.sampleVolumeField;
        }
        set
        {
            this.sampleVolumeField = value;
        }
    }

    /// <remarks/>
    public TemperatureUnitsType LidTemperature
    {
        get
        {
            return this.lidTemperatureField;
        }
        set
        {
            this.lidTemperatureField = value;
        }
    }

    /// <remarks/>
    public TemperatureUnitsType BlockTemperature
    {
        get
        {
            return this.blockTemperatureField;
        }
        set
        {
            this.blockTemperatureField = value;
        }
    }

    /// <remarks/>
    public float EstimatedRemainingRunTime
    {
        get
        {
            return this.estimatedRemainingRunTimeField;
        }
        set
        {
            this.estimatedRemainingRunTimeField = value;
        }
    }

    /// <remarks/>
    public string NickName
    {
        get
        {
            return this.nickNameField;
        }
        set
        {
            this.nickNameField = value;
        }
    }

    /// <remarks/>
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public int Rows
    {
        get
        {
            return this.rowsField;
        }
        set
        {
            this.rowsField = value;
        }
    }

    /// <remarks/>
    public int Columns
    {
        get
        {
            return this.columnsField;
        }
        set
        {
            this.columnsField = value;
        }
    }

    /// <remarks/>
    public BlockLetterType Letter
    {
        get
        {
            return this.letterField;
        }
        set
        {
            this.letterField = value;
        }
    }

    /// <remarks/>
    public bool Dual
    {
        get
        {
            return this.dualField;
        }
        set
        {
            this.dualField = value;
        }
    }

    /// <remarks/>
    public bool RealTime
    {
        get
        {
            return this.realTimeField;
        }
        set
        {
            this.realTimeField = value;
        }
    }

    /// <remarks/>
    public string Manufacturer
    {
        get
        {
            return this.manufacturerField;
        }
        set
        {
            this.manufacturerField = value;
        }
    }

    /// <remarks/>
    public bool Simulated
    {
        get
        {
            return this.simulatedField;
        }
        set
        {
            this.simulatedField = value;
        }
    }

    /// <remarks/>
    public string RipFolder
    {
        get
        {
            return this.ripFolderField;
        }
        set
        {
            this.ripFolderField = value;
        }
    }

    /// <remarks/>
    public MotorizedLidPositionType MotorizedLidPosition
    {
        get
        {
            return this.motorizedLidPositionField;
        }
        set
        {
            this.motorizedLidPositionField = value;
        }
    }

    /// <remarks/>
    public int BlockID
    {
        get
        {
            return this.blockIDField;
        }
        set
        {
            this.blockIDField = value;
        }
    }

    /// <remarks/>
    public bool ShippingScrewInstalled
    {
        get
        {
            return this.shippingScrewInstalledField;
        }
        set
        {
            this.shippingScrewInstalledField = value;
        }
    }

    /// <remarks/>
    public SerialNumbersType SerialNumbers
    {
        get
        {
            return this.serialNumbersField;
        }
        set
        {
            this.serialNumbersField = value;
        }
    }

    /// <remarks/>
    public FirmwareVersionsType FirmwareVersions
    {
        get
        {
            return this.firmwareVersionsField;
        }
        set
        {
            this.firmwareVersionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class ErrorType
{

    private System.DateTime dateTimeField;

    private string errorCodeField;

    private string errorDescriptionCurrentCultureField;

    private string errorDescriptionInvariantCultureField;

    /// <remarks/>
    public System.DateTime DateTime
    {
        get
        {
            return this.dateTimeField;
        }
        set
        {
            this.dateTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }

    /// <remarks/>
    public string ErrorDescriptionCurrentCulture
    {
        get
        {
            return this.errorDescriptionCurrentCultureField;
        }
        set
        {
            this.errorDescriptionCurrentCultureField = value;
        }
    }

    /// <remarks/>
    public string ErrorDescriptionInvariantCulture
    {
        get
        {
            return this.errorDescriptionInvariantCultureField;
        }
        set
        {
            this.errorDescriptionInvariantCultureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public enum StatusType
{

    /// <remarks/>
    Idle,

    /// <remarks/>
    Paused,

    /// <remarks/>
    Running,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Infinite Hold")]
    InfiniteHold,

    /// <remarks/>
    Synchronizing,

    /// <remarks/>
    Calibrating,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lid Open")]
    LidOpen,

    /// <remarks/>
    Initializing,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Waiting Manual Start")]
    WaitingManualStart,

    /// <remarks/>
    Processing,

    /// <remarks/>
    Preserving,

    /// <remarks/>
    Error,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Local Run")]
    LocalRun,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public enum BlockLetterType
{

    /// <remarks/>
    A,

    /// <remarks/>
    B,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public enum MotorizedLidPositionType
{

    /// <remarks/>
    OPEN,

    /// <remarks/>
    CLOSED,

    /// <remarks/>
    OPENING,

    /// <remarks/>
    CLOSING,

    /// <remarks/>
    UNKNOWN,

    /// <remarks/>
    MANUAL,

    /// <remarks/>
    NONE,

    /// <remarks/>
    STOP,

    /// <remarks/>
    ERROR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class SkipStepType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class QueryInstrumentBlocksType
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class ShutDownType
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class StopRunType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class ResumeRunType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class PauseRunType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class FlashLedType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class CloseLidType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class OpenLidType
{

    private string serialNumberField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class AnalysisExportType
{

    private string dataFileField;

    private string outputFileField;

    /// <remarks/>
    public string DataFile
    {
        get
        {
            return this.dataFileField;
        }
        set
        {
            this.dataFileField = value;
        }
    }

    /// <remarks/>
    public string OutputFile
    {
        get
        {
            return this.outputFileField;
        }
        set
        {
            this.outputFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class GenerateReportType
{

    private ReportTypes typeField;

    private string dataFileField;

    private string templateFileField;

    private string outputFileField;

    /// <remarks/>
    public ReportTypes Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string DataFile
    {
        get
        {
            return this.dataFileField;
        }
        set
        {
            this.dataFileField = value;
        }
    }

    /// <remarks/>
    public string TemplateFile
    {
        get
        {
            return this.templateFileField;
        }
        set
        {
            this.templateFileField = value;
        }
    }

    /// <remarks/>
    public string OutputFile
    {
        get
        {
            return this.outputFileField;
        }
        set
        {
            this.outputFileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public enum ReportTypes
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("txt)")]
    txt,

    /// <remarks/>
    pdf,

    /// <remarks/>
    mht,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class RunProtocolType
{

    private string serialNumberField;

    private string protocolFileField;

    private string plateFileField;

    private string noteField;

    private string runIdField;

    private string dataFileField;

    private bool lockInstrumentPanelField;

    private bool generateReportEndOfRunField;

    private ReportTypes generateReportTypeField;

    private string generateReportTemplateFileField;

    private string generateReportOutputFileField;

    private string emailAddressesField;

    /// <remarks/>
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }

    /// <remarks/>
    public string ProtocolFile
    {
        get
        {
            return this.protocolFileField;
        }
        set
        {
            this.protocolFileField = value;
        }
    }

    /// <remarks/>
    public string PlateFile
    {
        get
        {
            return this.plateFileField;
        }
        set
        {
            this.plateFileField = value;
        }
    }

    /// <remarks/>
    public string Note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }

    /// <remarks/>
    public string RunId
    {
        get
        {
            return this.runIdField;
        }
        set
        {
            this.runIdField = value;
        }
    }

    /// <remarks/>
    public string DataFile
    {
        get
        {
            return this.dataFileField;
        }
        set
        {
            this.dataFileField = value;
        }
    }

    /// <remarks/>
    public bool LockInstrumentPanel
    {
        get
        {
            return this.lockInstrumentPanelField;
        }
        set
        {
            this.lockInstrumentPanelField = value;
        }
    }

    /// <remarks/>
    public bool GenerateReportEndOfRun
    {
        get
        {
            return this.generateReportEndOfRunField;
        }
        set
        {
            this.generateReportEndOfRunField = value;
        }
    }

    /// <remarks/>
    public ReportTypes GenerateReportType
    {
        get
        {
            return this.generateReportTypeField;
        }
        set
        {
            this.generateReportTypeField = value;
        }
    }

    /// <remarks/>
    public string GenerateReportTemplateFile
    {
        get
        {
            return this.generateReportTemplateFileField;
        }
        set
        {
            this.generateReportTemplateFileField = value;
        }
    }

    /// <remarks/>
    public string GenerateReportOutputFile
    {
        get
        {
            return this.generateReportOutputFileField;
        }
        set
        {
            this.generateReportOutputFileField = value;
        }
    }

    /// <remarks/>
    public string EmailAddresses
    {
        get
        {
            return this.emailAddressesField;
        }
        set
        {
            this.emailAddressesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class UnRegisterServiceType
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
public partial class RegisterServiceType
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Blocks", Namespace = "http://schemas.bio-rad.com/LSG/GXD/CfxComSchema.xsd", IsNullable = false)]
public partial class InstrumentBlocksType
{

    private string cFXManagerVersionField;

    private string userField;

    private string registrationIDField;

    private ErrorType[] errorArrayField;

    private InstrumentBlockType[] blockArrayField;

    /// <remarks/>
    public string CFXManagerVersion
    {
        get
        {
            return this.cFXManagerVersionField;
        }
        set
        {
            this.cFXManagerVersionField = value;
        }
    }

    /// <remarks/>
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }

    /// <remarks/>
    public string RegistrationID
    {
        get
        {
            return this.registrationIDField;
        }
        set
        {
            this.registrationIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ErrorArray")]
    public ErrorType[] ErrorArray
    {
        get
        {
            return this.errorArrayField;
        }
        set
        {
            this.errorArrayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BlockArray")]
    public InstrumentBlockType[] BlockArray
    {
        get
        {
            return this.blockArrayField;
        }
        set
        {
            this.blockArrayField = value;
        }
    }
}
